language: php

php:
  - "5.4"
  - "5.3"

before_install:
  - cd ../../
  - git clone git://github.com/laravel/laravel.git
  - mv ./raftalks/Laravel_Theme_Bundle ./laravel/bundles/theme
  - echo "<?php return array('theme' => array('auto' => true));" > ./laravel/application/bundles.php
  - cd ./laravel

script: "php artisan test theme"
